### ISSUE TITLE
How to convert .mot to .csv

### ISSUE THREAD

**Issue by Vinayky86** [JonathanCamargo/BlendOsim#1]
Hi thanks for this addon, but i have an issue, Opensim save motion file in .mot, and it’s not working in blender import, how to convert it to .csv

**Comment by JonathanCamargo** [comment]
I use https://github.com/JonathanCamargo/MoCapTools to interface with OpenSim.  This produces Matlab tables that can be saved to csv (csvwrite or writematrix). Let me know if that could work for you or we can work on adding some functionality to parse mot files.

**Comment by Vinayky86** [comment]
Thanks for quick response sir. Can it be possible in addon to directly access .mot file, actually I’m not a programming guy. I send you my data https://drive.google.com/file/d/1BrRPLE9QQ34s6kdZBAHC1KcMJanpfT3C/view?usp=drivesdk

i use pose2sim for mocap and final results store in .mot file. If it possible for you with little effort then it’s yours big kindness for me. Thanks 🙏🙏❤️❤️

**Comment by Vinayky86** [comment]
https://gitlab.inria.fr/perfanalytics/pose2sim
this repo i use for mocap

**Comment by carlosedubarreto** [comment]
there is an option on Inver kinematics tool that when you enable it, opensim exports the location data.
you have to add this flag
`<report_marker_locations>true</report_marker_locations>`

This flag you can add on the xml file loaded to use with ik tool, you you can use a tool in opensim to change this information.

and a file names "_ik_model_marker_locations.sto" will be created at the home folder.

I'm almost sure that this thing I've explanined will work. I've done it a few months ago.

**Comment by Vinayky86** [comment]
Thank you very much sir..🙏😊
