### ISSUE TITLE
Plug-in cannot be installed

### ISSUE THREAD

**Issue by XzavierDion** [JonathanCamargo/BlendOsim#3]
<img width="661" alt="install" src="https://user-images.githubusercontent.com/34223067/218418872-d4ea2996-3fe8-4187-a338-2c5f3de0223c.png">

<img width="1724" alt="installed" src="https://user-images.githubusercontent.com/34223067/218419001-1aff0936-c517-470e-957e-3345f0705525.png">

The installed plug-in cannot be found！

**Comment by JonathanCamargo** [comment]
Please use the search bar, type blendosim and it should show the add on. Let me know if that works.

**Comment by XzavierDion** [comment]
<img width="659" alt="截屏2023-02-14 10 03 40" src="https://user-images.githubusercontent.com/34223067/218619999-a44bb0bf-51b8-46ff-a44f-16b3fd9efa60.png">

This add-on cannot be found，after installed.

**Comment by JonathanCamargo** [comment]
Can you share the exact version of blender you're using?

**Comment by XzavierDion** [comment]
<img width="1428" alt="截屏2023-02-14 10 29 30" src="https://user-images.githubusercontent.com/34223067/218623568-cc77cd89-2f83-40ba-b2fd-fac290574d98.png">

**Comment by JonathanCamargo** [comment]
I just tried on 3.0.0 and it works, that could get you started while I test on 2.80.

**Comment by JonathanCamargo** [comment]
Tested on 2.83 LTS and it also works. I can't find the 2.80 version. Please reopen if >2.83 does not work for you.
